### ISSUE TITLE
Allow different seedphrase lengths

### ISSUE THREAD

**Issue by ezxpro** [merland/seedpicker#52] opened 2022-04-20 13:05 UTC
I've been making a few tests with incomplete seedphrases and checking the checksum with seedpicker is faster than calculating it myself.

However, I'd very much like to see seedpicker work with at least 11 word passphrases, possibly other lengths too

**Comment by merland** [comment] 2022-04-26 09:39
Duplicate of #14

**Closed by merland** 2022-04-26 09:39 UTC
